typography_spectrum: 0.9438373517241365
color:
  brandColors:
    - '#6B757E'
    - '#ABB0B4'
    - '#435724'
    - '#D1D2CD'
    - '#1D2414'
  brandStrength: 0.9366696738358588
  lightness: 0.8038946207202419
  saturation: 0.4587821167400383
  rhythmicContrast: 0.5975306227075692
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7079471315188093
analytics:
  google: UA-67181126-1
  facebook: null
  twitter: null
author:
  name: Christopher Carlson
  email: Chris@cta.cloud
  url: 'http://chriscarlson.me'
logo: null
name: Chris Carlson - Thinking Out Loud
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Making HP-LED Light Systems
    id: 2ee317e6-3ddc-4d1c-88e0-0e0c2bea4680
    type: content
  - name: Internet Neighboring
    id: 225f46ff-6e7d-44c9-90cf-3b93c650c9fa
    type: content
  - name: An Excellent Read
    id: b84ba643-d4da-4906-8aff-3521b4f02bff
    type: content
  - name: Why I Want to Depart
    id: 3d453bff-d410-4d13-9a72-8bb8dba2d5c3
    type: content
  - name: Education & Experience
    id: 776c835f-5547-4b06-9abf-11f4581339f9
    type: content
  - name: The Grid - Design with Ease
    id: 6083f50f-091e-4452-bee8-66baa8f91039
    type: content
  - name: Work & Play
    id: 0c4bdb38-8844-4967-83a4-c91c55a5c602
    type: content
  - name: My Wedding
    id: 65d82db9-f888-45f6-8a8f-2c15896d28ee
    type: content
  - name: Military Service
    id: 04703952-78bc-4b49-a60b-24be2afe79be
    type: content
  - name: Childhood
    id: afb9c682-1508-4f01-a41a-39213bd74e98
    type: content
  - name: Terrific Kids
    id: 937efe30-a0ee-4bbc-8789-69066a19a22c
    type: content
  - name: Press Credentials
    id: a0acd150-c6bd-447e-ae4a-d800547bc8c0
    type: content
  - name: 'Systemback: A Sweet Linux System Backup Utility'
    id: 06bbbb61-49a1-4800-8275-806696ec1132
    type: content
  - name: 'Cloud Storage that is Distributed, Encrypted, Cheap'
    id: 4efa58f4-9e90-4c74-b54a-f62d4f27be38
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/53989fba-e97c-4a1f-8289-cb8d269fbaf4.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Chris Carlson
content: []
description: Thinking Out Loud
purpose: []
